apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demop
  template:
    metadata:
      labels:
        app: demop
    spec:
      containers:
      - name: demop
        image: djtoler/hwthdemoapp2:latest
        ports:
        - containerPort: 80
